main: me.zombie_striker.npcauctions.Main
version: 1.0.36
name: NPCAuctions
commands:
  NPCAuction:
    description: Toggles between NPC and villager
    aliases: [npca]
permissions:
  npcauctions.*:
    description: Gives access to all NPCAuction commands
    children:
      npcauctions.create: true
      npcauctions.destroy: true
      npcauctions.bypasslimit: true
  npcauctions.auctionlimit.1:
    description: limits the auction to 1
author:
   Zombie_Striker
softdepend: [Vault, Citizens]