main: me.zombie_striker.npcauctions.Main
version: 1.0.55
name: NPCAuctions
api-version: 1.13
commands:
  NPCAuction:
    description: Toggles between NPC and villager
    aliases: [npca]
permissions:
  npcauctions.*:
    description: Gives access to all NPCAuction commands
    children:
      npcauctions.create: true
      npcauctions.destroy: true
      npcauctions.bypasslimit: true
      npcauctions.default: true
      npcauctions.endall: true
  npcauctions.auctionlimit.1:
    description: limits the auction to 1
  npcauctions.default:
    default: true
    description: Gives access to all PixelPrinter commands
    children:
      npcauctions.openGUIFromCommand: true
author:
   Zombie_Striker
softdepend: [Vault, Citizens]